# Generated by Django 6.0.3 on 2026-03-30 16:19

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AnalysisResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('forgery_status', models.CharField(choices=[('pending', 'Pending Analysis'), ('authentic', 'Authentic - No Forgery Detected'), ('suspicious', 'Suspicious - Possible Forgery'), ('forged', 'Forged - Manipulation Detected')], default='pending', max_length=20)),
                ('confidence_score', models.FloatField(blank=True, help_text='Confidence score (0-100) of the forgery detection', null=True)),
                ('ela_image', models.ImageField(blank=True, help_text='Error Level Analysis visualization', null=True, upload_to='uploads/ela/%Y/%m/%d/')),
                ('ela_score', models.FloatField(blank=True, help_text='ELA-based forgery score', null=True)),
                ('ela_threshold_exceeded', models.BooleanField(default=False)),
                ('heatmap_image', models.ImageField(blank=True, help_text='Heatmap showing suspicious regions', null=True, upload_to='uploads/heatmap/%Y/%m/%d/')),
                ('overlay_image', models.ImageField(blank=True, help_text='Heatmap overlay on original image', null=True, upload_to='uploads/overlay/%Y/%m/%d/')),
                ('analysis_started_at', models.DateTimeField(blank=True, null=True)),
                ('analysis_completed_at', models.DateTimeField(blank=True, null=True)),
                ('processing_time', models.FloatField(blank=True, help_text='Processing time in seconds', null=True)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Analysis Result',
                'verbose_name_plural': 'Analysis Results',
                'ordering': ['-analysis_completed_at'],
            },
        ),
        migrations.CreateModel(
            name='UploadedImage',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('original_image', models.ImageField(help_text='The original uploaded image file', upload_to='uploads/original/%Y/%m/%d/')),
                ('filename', models.CharField(blank=True, max_length=255)),
                ('file_size', models.BigIntegerField(blank=True, null=True)),
                ('image_format', models.CharField(blank=True, max_length=10)),
                ('width', models.IntegerField(blank=True, null=True)),
                ('height', models.IntegerField(blank=True, null=True)),
                ('uploaded_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('processed', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Uploaded Image',
                'verbose_name_plural': 'Uploaded Images',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='MetadataAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('software_detected', models.CharField(blank=True, max_length=500)),
                ('editing_software_found', models.BooleanField(default=False)),
                ('camera_make', models.CharField(blank=True, max_length=100)),
                ('camera_model', models.CharField(blank=True, max_length=100)),
                ('datetime_original', models.CharField(blank=True, max_length=100)),
                ('datetime_digitized', models.CharField(blank=True, max_length=100)),
                ('datetime_modified', models.CharField(blank=True, max_length=100)),
                ('timestamp_inconsistent', models.BooleanField(default=False)),
                ('has_gps_data', models.BooleanField(default=False)),
                ('gps_latitude', models.CharField(blank=True, max_length=50)),
                ('gps_longitude', models.CharField(blank=True, max_length=50)),
                ('metadata_json', models.TextField(blank=True)),
                ('suspicious_indicators', models.TextField(blank=True)),
                ('metadata_score', models.FloatField(blank=True, help_text='Metadata-based suspicion score (0-100)', null=True)),
                ('analysis_result', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='metadata_analysis', to='detection.analysisresult')),
            ],
            options={
                'verbose_name': 'Metadata Analysis',
                'verbose_name_plural': 'Metadata Analyses',
            },
        ),
        migrations.CreateModel(
            name='SuspiciousRegion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x1', models.FloatField(help_text='Top-left x coordinate')),
                ('y1', models.FloatField(help_text='Top-left y coordinate')),
                ('x2', models.FloatField(help_text='Bottom-right x coordinate')),
                ('y2', models.FloatField(help_text='Bottom-right y coordinate')),
                ('confidence', models.FloatField(help_text='Confidence level of this region being forged (0-100)')),
                ('area_size', models.IntegerField(blank=True, help_text='Area in pixels', null=True)),
                ('detection_method', models.CharField(default='ELA', help_text='Method used to detect this region', max_length=50)),
                ('analysis_result', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suspicious_regions', to='detection.analysisresult')),
            ],
            options={
                'verbose_name': 'Suspicious Region',
                'verbose_name_plural': 'Suspicious Regions',
                'ordering': ['-confidence'],
            },
        ),
        migrations.AddField(
            model_name='analysisresult',
            name='image',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='analysis_result', to='detection.uploadedimage'),
        ),
        migrations.CreateModel(
            name='AnalysisLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('level', models.CharField(choices=[('DEBUG', 'Debug'), ('INFO', 'Info'), ('WARNING', 'Warning'), ('ERROR', 'Error')], default='INFO', max_length=10)),
                ('message', models.TextField()),
                ('details', models.TextField(blank=True)),
                ('image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='detection.uploadedimage')),
            ],
            options={
                'verbose_name': 'Analysis Log',
                'verbose_name_plural': 'Analysis Logs',
                'ordering': ['-timestamp'],
            },
        ),
    ]
