# Generated by Django 6.0.3 on 2026-04-02 01:33
# Drops GPS columns from metadata (privacy). Also removes legacy overlay_image
# column that was dropped from AnalysisResult model earlier.

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('detection', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='analysisresult',
            name='overlay_image',
        ),
        migrations.RemoveField(
            model_name='metadataanalysis',
            name='gps_latitude',
        ),
        migrations.RemoveField(
            model_name='metadataanalysis',
            name='gps_longitude',
        ),
        migrations.RemoveField(
            model_name='metadataanalysis',
            name='has_gps_data',
        ),
    ]
