# Generated by Django 6.0.3 on 2026-04-16 15:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('detection', '0002_remove_metadata_gps_fields'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AnalysisLog',
        ),
    ]
